### ISSUE TITLE
There is a bug.

### ISSUE THREAD

**Issue by Perezari** [fredatgithub/FamilyShow#1] opened 2020-01-30 06:42 UTC
When I drag a picture of a person into the window, I get an error.
Can you fix it?

**Comment by fredatgithub** [comment] 2020-03-10 17:17
What is your error message ?

**Comment by fredatgithub** [comment] 2020-03-10 17:18
Can you join a screen  capture ?

**Comment by fredatgithub** [comment] 2020-03-10 17:30
I cannot reproduce the bug
Can you describe each step in order for me to reproduce the bug ?

**Comment by fredatgithub** [comment] 2020-03-10 18:06
bug reproduced

**Comment by fredatgithub** [comment] 2020-03-10 18:08
Bug fixed in version 3.2

**Closed as completed** 2020-06-21 20:44 UTC
